name: Build and Deploy to Azure App Service

on:
  push:
    branches:
      - main  # Asegúrate de que esta sea tu rama principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v3

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: containeredurag.azurecr.io
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build . -t containeredurag.azurecr.io/eduragapp:latest
        docker push containeredurag.azurecr.io/eduragapp:latest

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      run: |
        az webapp config container set --name EduRag --resource-group edurag --docker-custom-image-name containeredurag.azurecr.io/eduragapp:latest
